//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker_test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public int User_Id { get; set; }
        public Nullable<System.DateTime> Log_IN { get; set; }
        public Nullable<System.DateTime> Log_OUT { get; set; }
        public bool LogStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
