//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker_test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionId { get; set; }
        public string QuestionTitle { get; set; }
        public string Q_A { get; set; }
        public string Q_B { get; set; }
        public string Q_C { get; set; }
        public string Q_D { get; set; }
        public string Q_CorrectAnswer { get; set; }
        public Nullable<int> QuizId { get; set; }
    
        public virtual Quiz Quiz { get; set; }
    }
}
